### ISSUE TITLE
Quantum Design PPMS data

### ISSUE THREAD

**Issue by SeregaKR** [greigpaterson/HystLab#1]
Hello.
I'm trying to use the program to process hysteresis loop. I have 3 different measurements of the same sample saved to dat file (Quantum Design PPMS file format). I attach 2 of them below (renamed from dat to txt because of the GitHub).
[DPCA95_1T.txt](https://github.com/greigpaterson/HystLab/files/3945714/DPCA95_1T.txt)
[DPCA95_2T.txt](https://github.com/greigpaterson/HystLab/files/3945715/DPCA95_2T.txt)
I encountered 2 problems so far.

One measurement was done from -2T to +2T. When I load the data the fitted loop range is from -1.5T to +1.5T. Why does the load process lose so much data?
![loop](https://user-images.githubusercontent.com/1452103/70544479-6bf72b80-1b6c-11ea-94e9-9af1652634c0.jpg)

One measurement was done from -1T to +1T. When I try to load it I receive an error Processing error, "file could not be correctly processed. Processing aborted". But the format of the two files is identical. What can be an issue here?

**Comment by SeregaKR** [comment]
I tried using it in Matlab R2015b and R2016b

**Comment by greigpaterson** [comment]
Hi SeregaKR,

Thanks for trying out HystLab, sorry to hear you have had issues. 

The MPMS/PPMS data files are quite complex in that they can contain multiple types of measurement data in addition to hysteresis loops. It is possible to have almost any type of measurements. Since the data file contains no information about the script, it very difficult to read all possible files that the MPMS/PPMS can generate.

At the moment, HystLab can handle an initial magnetization curve followed by the hysteresis loop. It separates these two data sets based on a change in the gradient of the field. Other data types in the file will mean the data are incorrectly read.

I have had a look at your data and there are a few things that HystLab couldn't handle. In the 2T file, it opens with a measurement that doesn't measure the moment, didn't expect that. I have now released v1.0.9, which should handle this better and read in the 2T file.

For the 1T file, there are about 55 or so data before the initial curve begins. Not sure what these are, but HystLab can't read them. I have trimmed these out in the attached file, which can be read in.

[DPCA95_1T_EDIT.txt](https://github.com/greigpaterson/HystLab/files/3946184/DPCA95_1T_EDIT.txt)

You should note that that both loops have several spurious data points that should be removed before processing.

Given the flexibility and diversity of the data that can be saved in an MPMS/PPMS data file, I'd strongly recommend saving different data type to different data files. This greatly eases the processing of all data types.

I hope this all helps.

Cheers
Greig

**Comment by SeregaKR** [comment]
Thank you for fast answer. I tried checking it - so far everything seems good.

**Comment by SeregaKR** [comment]
Hello again.
Sorry, but we have the problems with the data again. We measured PPMS and saved it to txt file as in the previous case. 
This dataset does not have the spikes, we leaved in the file only initial charge (from zero to max) and hysteresis loop itself. But still the data will not load.
Maybe it's possible to debug what was wrong with the data somehow so we will solve some problems ourselves?
[CR30_PY20_00004.txt](https://github.com/greigpaterson/HystLab/files/4107973/CR30_PY20_00004.txt)

**Comment by greigpaterson** [comment]
Hi SeregaKR,

I have push a quick fix for this to the repo. It was an issue with the reading of the header line to find where the field and moments are. These formats can be quick variable from different versions. In this case the field units are in cgs and the moments in SI. The fix should sort it.

If you download the Read_Hyst_File.m from the repo this has the fix. I've put it in a release yet, as I want to tidy it up a bit more.

Let me know how it goes.

Cheers
Greig

**Comment by SeregaKR** [comment]
Yes, mistake is gone now... thank you.
We tried making all the measurements in SI but obviously we managed only half way
