### ISSUE TITLE
Correction of hystersis cycle 

### ISSUE THREAD

**Issue by Abdou137** [greigpaterson/HystLab#2]
Dear all, 
I would like to ask if there is possibilty to fix the attached hystersis cycle: the attached loop is not closed , I tried to close it usign "upper branch" in drift correction, but it gave me two branches seperated , I ask if there is a way to get a closed one without a gap between the two branches . 
I attached the data file, please have a look. 
thank you very much for your help and comprehnsion 
with nice regar
[loop.txt](https://github.com/greigpaterson/HystLab/files/6541334/loop.txt)

ds

**Comment by greigpaterson** [comment]
Hi,

Thanks for trying out HystLab. 
This loop has a noisy excursion on the lower branch at fields around 1.4-1.5 T, which causes issues with the drift correction.
If you trim off fields greater than ~1350 mT and apply symmetric averaging it should give something reasonable. 

All the best
Greig

**Comment by Abdou137** [comment]
HI,
I tried to correct a hysteresis loop as an attachment. the software correctly displays the raw data but it does not make any corrections. it shows me the following window :
![image](https://user-images.githubusercontent.com/68156608/121501277-5e2f9a00-c9df-11eb-907a-c23d1500fb64.png)
[test.log](https://github.com/greigpaterson/HystLab/files/6630102/test.log)

**Comment by greigpaterson** [comment]
Hi,

It's always good to check the raw data when something goes wrong, as your loop is not a typical hysteresis loop and will probably need remeasured.

The offset is extremely large and then negative field half gives a more positive moment response than the positive field have. Since this does not appear to be a diamagnetically dominated sample, it would suggest that sample is not centered in the measurement region.

I guess this is measured on a SQUID system? MPMS? PPMS? In these systems, away from the central measurement region, the SQUIDs have a negative response. This produces the inverted hysteresis loop that you have here. The only reliable fix is to remeasure the data, making sure that the specimen is correctly centered in the measurement region.

![Test_Loop](https://user-images.githubusercontent.com/7586312/121512274-730d2d00-c9e1-11eb-80c6-4175025118be.png)

**Comment by Abdou137** [comment]
hi!
i tried to do another cycle. The software reads the file , but it plot but it doesn't make data processing.
i use the MOKE magnemotry
[essai.txt](https://github.com/greigpaterson/HystLab/files/6632396/essai.txt)

**Comment by greigpaterson** [comment]
For clarity, I am closing this issue and opening a new one for this new data
